- name: installing mongodb
  hosts: mongodb
  become: yes
  tasks:

  - name: Copy file mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb-org
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

  - name: Starting and enabling mongod service
    ansible.builtin.service:
      name: mongod
      enabled: true
      state: started
  
  - name: Replacing 127.0.0.1 to 0.0.0.0
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Retarting mongod service
    ansible.builtin.service:
      name: mongod
      state: restarted